apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ouja
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-ouja@sha256:e1067a0a75bd0d479f26ea8c9581571a9cf5cfd29e210d7519676225c898a703
        name: my-nodejs
        resources: {}
status: {}
